version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: userservice-postgres-1
    environment:
      - POSTGRES_DB=robo_advisor
      - POSTGRES_USER=robo
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: