server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    reply:
      timeout: 15
    topic:
      replicationFactor: 1
      partitions: 1
      names:
        user-add-request-topic: user-add-request
        user-add-reply-topic: user-add-reply
        user-find-by-username-request-topic: user-find-by-username-request
        user-find-by-username-reply-topic: user-find-by-username-reply
    consumer:
      group-id: user-group



  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/robo_advisor
    username: robo
    password: password
  jpa:
    hibernate:
      ddl-auto: none